// Tiny href -> emoji map, safe to import from client components
// (no data imports, unlike lib/all-items)
export const subjectEmojis: Record<string, string> = {
  "/philosophie": "🏛️",
  "/litterature": "✍️",
  "/peinture": "🎨",
  "/cinema": "🎬",
  "/architecture": "🏗️",
  "/musique-classique": "🎼",
  "/inventions": "💡",
  "/astronomie": "🔭",
  "/medecine": "⚕️",
  "/explorations": "🧭",
  "/mouvements-politiques": "⚖️",
  "/mathematiques": "🔢",
  "/physique": "⚛️",
  "/biologie": "🧬",
  "/jazz": "🎺",
  "/economie": "📈",
  "/empires": "👑",
  "/esclavage": "⛓️",
  "/psychologie": "🧠",
  "/guerres": "⚔️",
  "/monnaies": "💰",
  "/religions": "🕊️",
  "/revolutions-industrielles": "🏭",
  "/pandemies": "🦠",
  "/epoques": "🦕",
  "/droits-civiques": "✊",
  "/democratie": "🗳️",
  "/mythologies": "🐉",
  "/photographie": "📷",
  "/arts-decoratifs": "🪑",
};
